export const FETCH_PASSENGERS = 'FETCH_PASSENGERS';
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const LOGOUT = 'LOGOUT';
export const ADD_INPUT_FLIGHT_ID = 'ADD_INPUT_FLIGHT_ID'
export const ADD_MODAL_DATA = 'ADD_MODAL_DATA'
export const UPDATE_PASSENGER_DETAILS = 'UPDATE_PASSENGER_DETAILS';
export const ADD_PASSENGER_DETAILS = 'ADD_PASSENGER_DETAILS';
export const ADD_ANCILLARY_SERVICES = 'ADD_ANCILLARY_SERVICES';
export const UPDATE_ANCILLARY_SERVICES = 'UPDATE_ANCILLARY_SERVICES';
export const DELETE_ANCILLARY_SERVICES = 'DELETE_ANCILLARY_SERVICES';
export const ADD_SPECIAL_MEALS = 'ADD_SPECIAL_MEALS';
export const UPDATE_SPECIAL_MEALS = 'UPDATE_SPECIAL_MEALS';
export const DELETE_SPECIAL_MEALS = 'DELETE_SPECIAL_MEALS';
export const ADD_SHOPPING_ITEMS = 'ADD_SHOPPING_ITEMS';
export const UPDATE_SHOPPING_ITEMS = 'UPDATE_SHOPPING_ITEMS';
export const DELETE_SHOPPING_ITEMS = 'DELETE_SHOPPING_ITEMS';

